language: php
sudo: false
dist: trusty

notifications:
  email: false

cache:
  directories:
    - $HOME/.composer/cache
    - vendor

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=trunk
    - php: 7.1
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest

install:
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist --no-scripts --no-suggest
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - ./vendor/bin/phpunit
